#!/bin/bash

logfile=/home/james/www/Stout/sandbox/coins/logs/cycleLog

echo "*****************************************" >> $logfile
echo " LOAD BTER DATA TO MYSQL                 " >> $logfile
echo "*****************************************" >> $logfile
wget -O - localhost/james/Stout/sandbox/coins/loadbter.php >> $logfile 2>&1
