#!/usr/bin/perl
use warnings;
use strict;

#my $arg1 = $ARGV[0];
my $arg1 = 'junk';
print "lets mechanize the $arg1 exchange...\n";

use WWW::Mechanize; my $mech = WWW::Mechanize->new(); $mech->timeout(56800);

my $url = 'http://www.mintpal.com'; $mech->get ( $url );
my $page = $mech->content();
print "page return:\n  $page\n";

=cut
$page =~ s/>/>\n/g;
my @lines = split(/\n/,$page);
my $special = '';
for(@lines){
	print "$_\n";
	if( $_ =~ /^<ifram/ ){
		$special = $_;
	}
}
$special =~ /src="([^"]+)"/;
print "\nSpeical\n  $1\n";

#$url = "http://www.mintpal.com$1"; $mech->get ( $url );
#$page = $mech->content();
#print "page return:\n  $page\n";
=cut

=cut
use DateTime;
#my $now = DateTime->now();
my $now = DateTime->now(time_zone => 'America/New_York');
my $stamp = $now->ymd('-') . ' ' . $now->hms(':');
print "************************\n";
print "Lets Mechanize - running upDate script\n";
print "time stamp: $stamp\n";
=cut

=cut
$mech->submit_form(
	form_number => 1,
	fields => {
		alice => 'tarman'
	}
);
=cut
