<html>
<head>
	<link rel='stylesheet' type='text/css' href='style.css' />
</head>
<body>
	<div id='exchange'>
		<div>Controls
			<div>mode</div>
			<div>
				<button>A</button>
				<button>B</button>
				<button>C</button>
			</div>
		</div>
		<div>accounts
			<div>USD
				<div>Amount</div>
			</div>
			<div>BTC
				<div>Amount</div>
				<div>Cost</div>
				<div>Net</div>
			</div>
		</div>
		<div>trader
			Auto <input type='radio' name='traderMode' value='auto' checked>
			Fixed<input type='radio' name='traderMode' value='fixed'>
			<div>Bid
				<div>Amount</div>
				<button>+</button>
				<button>-</button>
				<button>Bid</button>
			</div>
			<div>Ask
				<div>Amount</div>
				<button>+</button>
				<button>-</button>
			</div>
			<div>Size
				<div>Amount</div>
				<button>+</button>
				<button>-</button>
				<button>Ask</button>
			</div>
		</div>
		<div>orders
			<div>Bids
				<div>Open
					<div>Size</div>
					<div>Price</div>
					<div>Depth</div>
					<div>Spread</div>
					<button>Cancel</button>
				</div>
				<div>Closed</div>
			</div>
			<div>Asks
				<div>Open
					<div>Size</div>
					<div>Price</div>
					<div>Depth</div>
					<div>Spread</div>
					<button>Cancel</button>
				</div>
				<div>Closed</div>
			</div>
		</div>
		<div>book
			<div>Bid</div>
			<div>Spread</div>
			<div>Ask</div>
			<div>Bids</div>
			<div>Asks</div>
		</div>
		<div>trades
			<div>Buys</div>
			<div>Sells</div>
		</div>
	</div>
</body>
</html>